[tool.poetry]
name = "quantus-nlp"
version = "0.1.0"
description = ""
authors = ["Artem Sereda <Aitem1503@icloud.com>"]

[tool.poetry.dependencies]
python = "^3.8"
dvc = "^2.13.0"
flax = "^0.5.2"
transformers = "^4.20.1"
optax = "^0.1.3"
lit-nlp = "^0.4.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
